apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-deployment
  namespace: webapps
spec:
  selector:
    matchLabels:
      app: boardgame
  replicas: 1
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
        - name: boardgame
          image: talha884/boardshack:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "800Mi" # Increased slightly for Java stability
              cpu: "500m"
            limits:
              memory: "1.5Gi" # Increased to give Java more "breathing room"
              cpu: "1000m"
          # PROBES REMOVED TEMPORARILY TO DIAGNOSE CRASH
---
apiVersion: v1
kind: Service
metadata:
  name: boardgame-ssvc
  namespace: webapps
spec:
  selector:
    app: boardgame
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
      nodePort: 31178
  type: NodePort
